.snyk

Cleaning up the policy, extending `marked` vuln ignore duration

chore: snyk policy update

---

lib/snyk-to-html.js
snyk-to-html.js
test/fixtures/expected-output-empty-description-case.html
test/fixtures/test-report-empty-descr.json
test/snyk-to-html.test.js

Reported issues with the report generation. Turns out issues reported without description are causing a marked crash "replace not working on undefined". Slight tweak to handle these cases.

fix: crash on missing description

---

.releaserc
.travis.yml
package.json

This PR fixes #26 and allow to package `snyk-to-html` into an executable.
P.S.: The code is shamelessly "stolen" from snyk CLI repository.

chore: add pkg to semantic-release process

---

.releaserc

Finding a way to build a good standalone alpine image using `pkg`.
Naive `pkg . -t alpine` generates a broken binary (segfault on a plain alpine image). Generating one inside an alpine container works.

fix: add alpine platform to standalone binary release assets

---

src/lib/snyk-to-html.ts
template/test-report.hbs

Counting vulnerabilities was inconsistent between multi-reports and single-reports. In the former it based it on actually counting the vulns in the data provided and in the single-reports it used the response from the API
Both multi and single reports are now counting the total vulnerabilities based on the data provide
If a user is using `jq` to manipulate the data for a single report then the header would incorrectly show a different amount of vulns than those that were piped to it in the actual data

Fix: count vulns from data

---

package-lock.json
package.json
tsconfig.json

This removes some uses of tslib's promises from the generated code,
and generally cleans up stack traces and error messages.

feat: generate es2015 code for node 6+

---

Dockerfile
docker-entrypoint.sh

Packaging snyk-to-html as a Docker image makes using the tool in places
where installing a full Node toolchain is problematic or annoying. The
image also aims to make usage easier by outputting the html on stdout,
rather than writing a file to disk.
Using the -o and -i options the image can be used to read and/or write from
files on disk as well.

Added a Dockerfile to help with using snyk-to-html in pipelines

---

README.md
package-lock.json
package.json
src/index.ts
src/lib/snyk-to-html.ts
template/test-report.hbs
template/test-report.vuln-card.hbs
test/fixtures/test-report-with-no-remediation-and-no-fixed-in.json
test/fixtures/test-report-with-no-remediation-with-multiple-fixed-in.json
test/fixtures/test-report-with-no-remediation-with-one-fixed-in.json
test/snyk-to-html.test.ts

implementation for #22 
```cat test/fixtures/test-report.json | node dist/index.js  -o before.html```
```cat test/fixtures/test-report.json | node dist/index.js  -o before.html```

feat: add summary option in CLI

---

src/lib/snyk-to-html.ts
tap-snapshots/test-snyk-to-html.test.ts-TAP.test.js
test/snyk-to-html.test.ts

Addresses [https://github.com/snyk/snyk-to-html/issues/63](https://github.com/snyk/snyk-to-html/issues/63)
Vulnerabilities are now output in order of severity, from high to low.
Now:
Previous:

feat: sort report in descending order of severity and name

---

tap-snapshots/test-snyk-to-html.test.ts-TAP.test.js
template/test-report.hbs
template/test-report.inline-css.hbs
test/snyk-to-html.test.ts

Noticed the styling on test-report has been effected by new actionable remediation feature. Reverting back to the original style. There will be another PR to organise styles in this repo.

fix: css styling for test-report

---

package.json

The bug our tap fork is evading was fixed in around 2018. Switch back to the upstream tap, and get all the pretty things for free.

test: switch back to upstream tap

---

package.json

Updating dependencies to fix vulnerabilities
BREAKING CHANGE: Dropping Node 8 support
Snyk CLI dropped Node 8 support in Feb 2021 https://updates.snyk.io/ending-snyk-cli-support-for-node-js-8-x-183304

Update vulnerable dependency and drop Node.js 8 support

---

.github/workflows/test-and-release.yml

Add AWS env vars to the semantic-release step in GitHub actions.

chore: set AWS env vars in semantic-release step

---

.releaserc

Use node 14 for binary releases for compatibility with marked@2

Use node 14 for binary releases

---

src/lib/vuln.ts
template/iac/test-report.vuln-card.hbs

This PR fixed 2 issues:
1. Missing remediation in some reports
2. Wrong value for the K8 project type
[Slack Thread](https://snyk.slack.com/archives/CRV0PMFDH/p1638295682103400)

fix: Missing Remediation in IaC Reports

---

package.json
src/lib/snyk-to-html.ts
tap-snapshots/test-snyk-to-html.test.ts-TAP.test.js

to fix and supersede #114 
It appears that the test fixture markdown has some spaces that had previously been ignored by marked, so the html output is a bit different. I updated the tap snapshot using the TAP_SNAPSHOT=1 method to adjust the expected output from the tests.
none
n/a

chore: update marked to 4.0.12

---

package.json

Package.json incorrectly stated that license was ISC, but LICENSE file stated Apache 2

fix: define correct license in package.json

---

src/lib/codeutil.ts

This PR fixes a bug according to ZenDesk ticket [#23287](https://snyk.zendesk.com/agent/tickets/23287).
There was a problem showing the data flow analysis when there were whitespaces in the path to the file.
Before:
After:

fix: decode whitespace path for ticket 23287

---

tap-snapshots/test-snyk-to-html.test.ts-TAP.test.js
template/iac/test-report.vuln-card.hbs
test/fixtures/iac-test-report.json

This PR fixes some issues in IaC such as:
- when the line number is `-1` we don't want to show it
- when the rule doesn't have a documentation link we don't make the id a link and don't include an external link at the bottom of the card
- when the rule doesn't have an issue, impact, or remediation we don't show them (this is for custom rules only)
To test, run `node ./dist/index.js -i test/fixtures/iac-test-report.json -o results.html`
- [Link to issue](https://snyksec.atlassian.net/browse/CFG-1985)

fix: snyk-to-html for IaC [CFG-1985]

---

.github/CODEOWNERS

Cloud-dev-ex owns the plugin, group-infrastructure-as-code is deprecated.

chore: update CODEOWNERS for IaC

---

.releaserc

This PR introduces a change in the packaging command for our binaries to specify a default maximum old space size for V8's memory. The change was prompted by the need to accommodate larger projects that may require more memory than the default settings allow.
A change in the `pkg-fetch` repository (see [vercel/pkg-fetch@7f3403b](https://github.com/vercel/pkg-fetch/commit/7f3403bd71d244850ef30a711c52e64f905e9423)) disabled the `NODE_OPTIONS` environment variable, which previously allowed consumers to set Node.js runtime options, including `--max-old-space-size`, at runtime. This has impacted users who need to increase the memory limit beyond the default when running the `snyk-to-html` tool.
Given that we cannot rely on `NODE_OPTIONS`, this PR takes the approach of setting a conservative …

fix: include default `max_old_space_size` in binaries [HEAD-1045]

---

README.md

Small update to apply inline code block styling in the table description

docs: update code style in table

---

template/code/test-report.code-snip.hbs

Replicates the work from #169, but this time with signed commits ✨ 
**Before**
**After**

feat: include inline suppression comment

---

.github/workflows/test-and-release.yml
.releaserc

This PR increases the `max_old_space_size` node option, increasing the heap memory in the compiled binary. This should reduce the number of JS Heap OOM errors that may be encounterd.

chore: increase max_old_space_size in binaries

---

.github/workflows/test-and-release.yml

Updates CICD workflow to deprecate EOL node versions

chore: remove EOL node versions in CICD

---

package.json
src/lib/dateutil.ts
src/lib/snyk-to-html.ts
test/dateutil.test.ts

the moment dependency accounts for 59% of the bundle size of snyk-to-html pacakge and only used for a
simple (and predefined?) formatting option.
source: https://bundlephobia.com/package/snyk-to-html@2.5.1

feat: remove moment dependency

---

template/code/test-report.code-snip.hbs
template/code/test-report.inline-css.hbs
template/code/test-report.inline-js.hbs

Fix analysis is currently inaccessible in our Azure DevOps integration since the report uses JavaScript for switching between the dataflow and fix analysis tabs. This PR removes the need for JS by mimicking the behaviour by using two invisible radio buttons and some CSS styling.
How does this work? The magic lies on the two radio buttons added. Even if the input elements have `display: none`, clicking on the labels still triggers an input event, making it perfect for switching the tabs between fix and dataflow. The trickier part is syncing the state from the input elements to the dataflow and fix analysis content.
The CSS queries I used could be made a bit more simpler and shorter if I had use the `:has` selector, but I was unsure if the [browser support …

feat: remove use of JS for dataflow & fix analisys tabs
