snyk/snyk-to-html

package.json, snyk-to-html.js
Process stdin when no file was given
Removed arrow functions because Node 0.12
Separated into functions - I love callbacks!!
=> feat: process stdin when no file is given with -i

index.js
Added `#!/usr/bin/env node ` for running a node process
=> fix: adding node runtime instruction

.travis.yml, lib/snyk-to-html.js, package-lock.json, package.json, template/test-report.hbs, template/test-report.inline-css.hbs, test/fixtures/multi-test-report.json, test/snyk-to-html.test.js
Adds support for multi-project test results
Adds path(s) to generated page
removes a high-risk dependency imported via the semantic-release module
=> FEAT: Allows parsing of snyk test output generated from multiple project paths

.snyk, .travis.yml, package-lock.json, package.json, src/lib/snyk-to-html.ts, template/test-report.hbs, template/test-report.vuln-card.hbs
JIRA: https://snyksec.atlassian.net/browse/BST-79
Adding the first component of the ticket which is including the package manager in the vuln card.
=> feat: Add package manager name

README.md, package-lock.json, package.json, src/index.ts, src/lib/snyk-to-html.ts, test/fixtures/invalid-input.json, test/snyk-to-html.test.ts
=> feat: better error handling when running CLI

tap-snapshots/test-snyk-to-html.test.ts-TAP.test.js, template/test-report.hbs, test/fixtures/no-vulns.json, test/snyk-to-html.test.ts
=> feat: show a message when 0 vulns found

src/lib/snyk-to-html.ts, tap-snapshots/test-snyk-to-html.test.ts-TAP.test.js, template/new-report.hbs, template/test-report.hbs, template/test-report.header.hbs, template/test-report.inline-css.hbs
=> chore: extract header into partial, add snyk logo

src/lib/snyk-to-html.ts, tap-snapshots/test-snyk-to-html.test.ts-TAP.test.js, template/new-report.hbs, template/test-report.hbs, template/test-report.metatable-css.hbs, template/test-report.metatable.hbs
Adding in some scanned result meta
=> feat: introduce result meta table

.github/CODEOWNERS
Following the https://github.com/snyk/snyk/pull/1162
=> chore: add hammer as codeowner

package.json, src/lib/snyk-to-html.ts, template/test-cve-report.hbs, test/snyk-to-html.test.ts
New template for a customer request to present CVE data.
snyk-to-html -t template/test-cve-report.hbs
snyk-to-html.ts required modification to add required metadata fields from the source JSON.
=> feat: add cve report template and required metadata

src/index.ts, tap-snapshots/test-snyk-to-html.test.ts-TAP.test.js
Use synchronous write when writing output file.
Customer was having issue where the output file was still in use when a subsequent process tried to use it causing failure with downstream task.
ZD 8533
=> Use sync write output

src/lib/vuln.ts, tap-snapshots/test-snyk-to-html.test.ts-TAP.test.js, template/test-cve-report.hbs, template/test-report.inline-css.hbs, template/test-report.remediation-css.hbs, template/test-report.vuln-card.hbs, test/fixtures/expected-output.html, test/fixtures/test-report-with-critical-severity-vuln.json, test/snyk-to-html.test.ts, test/vuln.test.ts
* Adds support for vulnerabilities which have a `critical` severity. 
* Updates the colour palette to align with the recent product updates based on the values defined here:
https://www.figma.com/file/SEXtscLIly0HIPrapIj6OR/Severity-color-palette---Security?node-id=207%3A133
=> feat: adds support for critical severity [APOLLO-91]

tap-snapshots/test-snyk-to-html.test.ts-TAP.test.js, template/remediation-report.hbs, template/test-cve-report.hbs, template/test-report.hbs, test/fixtures/expected-output.html
To improve experience when using the report in an iframe
=> feat: open links in new window

.github/CODEOWNERS, src/lib/snyk-to-html.ts, src/lib/vuln.ts, tap-snapshots/test-snyk-to-html.test.ts-TAP.test.js, template/iac/test-report.hbs, template/iac/test-report.header.hbs, template/iac/test-report.inline-css.hbs, template/iac/test-report.inline-js.hbs, template/iac/test-report.metatable-css.hbs, template/iac/test-report.metatable.hbs, template/iac/test-report.vuln-card.hbs, test/fixtures/iac-test-report.json, test/snyk-to-html.test.ts
Up until now, snyk-to-html didn't support `snyk iac test --json` output.
In this PR we add support for this functionality.
- [CFG-1169](https://snyksec.atlassian.net/browse/CFG-1169)
=> feat: Add IaC Support

package.json
=> Add uglify-js to dependencies to resolve a vulnerability

package.json, src/lib/codeutil.ts, src/lib/snyk-to-html.ts, src/lib/vuln.ts
- removing use of custom forked lodash
- updating `moment`
=> Updating vulnerable dependencies

README.md
doc: supdateandsignmultiproductchangess
Update snyk to html to refer to multi product support.
Customers often don't realize it works across products
=> docs: update and signmulti product changes

.github/workflows/test-and-release.yml, tap-snapshots/test-snyk-to-html.test.ts-TAP.test.js
_Changes workflow trigger from `on push` to `on pull_request` and `on workflow_dispatch`_
=> chore: trigger workflow runs on PRs

.github/CODEOWNERS
=> chore: update codeowners with new team identifer

.circleci/config.yml, catalog-info.yaml
=> chore: update codeowners with new team identifer (@snyk/cli)

.github/CODEOWNERS
Updates repo to align with single owner goal
=> chore: simplify ownership policy

README.md
I have included a section called "getting support for snyk-to-html" to clarify the support terms for this tool.
To clarify support terms for snyk-to-html for our customers, I am including a section called _Getting support for snyk-to-html_
Please review the text and let me know if you have any questions.
Not applicable.
Not applicable.
=> Update README.md with a section for support terms

.github/workflows/test-and-release.yml
=> chore: update CICD to use node20

.releaserc
Updates semantic-release rules so chores (such as increasing heap memory size) triggers a patch release
=> chore: update commit-analyzer versioning rules

README.md
=> docs: add paragraph about release process
